[package]
name = "fforcha"
description = "FFmpeg Orchestrator"
authors = ["Linas Nikiperavičius <linas@linasdev.com>"]
license = "MIT"
version = "0.1.0"
edition = "2024"

[dependencies]
config = "0.15.24"
async-trait = "0.1.91"
log = "0.4.33"
env_logger = "0.11.11"
futures = "0.3.33"
async-walkdir = "2.1.0"
inotify = "0.11.4"
http = "1.4.2"
scc = "3.8.6"
serde_json = "1.0.151"
nanoid = "0.5.0"

[dependencies.serde]
version = "1.0.228"
features = ["derive"]

[dependencies.tokio]
version = "1.53.1"
features = ["macros", "sync", "fs", "rt-multi-thread"]

[dependencies.tokio-util]
version = "0.7.19"
features = ["time"]

[dependencies.tokio-websockets]
version = "0.13.3"
features = ["client", "server", "ring", "rand", "rustls-native-roots"]
